.PHONY: install test coverage compile clean

install:
	npm install

test:
	npx hardhat test

coverage:
	npx hardhat coverage

compile:
	npx hardhat compile

clean:
	npx hardhat clean
	rm -rf coverage coverage.json